[build]
  base = "."
  command = "pnpm install --frozen-lockfile && pnpm --filter web build"
  publish = "web/dist"

[build.environment]
  NODE_VERSION = "22"
  PNPM_VERSION = "10.16.0"
  NPM_FLAGS = "--version"
  VITE_SUPABASE_URL = "https://bbonxxvifycwpoeaxsor.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJib254eHZpZnljd3BvZWF4c29yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0Mjg5NDUsImV4cCI6MjA3MDAwNDk0NX0.rUuAcPIHVCfpAMEU2ADyb0F4Q3_eL0mkEyhBcbu0O70"
  VITE_APP_URL = "https://dislinkboltv2duplicate.netlify.app"
  VITE_SITE_URL = "https://dislinkboltv2duplicate.netlify.app"
  VITE_GEOCODING_API_KEY = "AIzaSyBFWDLn8_ifGfI7t3yx17JjMzjwpX7cwUA"
  VITE_GOOGLE_SHEETS_WEBHOOK_URL = "https://script.google.com/macros/s/AKfycbzZPJLqgrxcb1rn0BKJen080uiqJJBjXMkdv2d2CB3chdORB9TwdFWTJXKHslppDAtH/exec"

# Handle email confirmation redirects from Supabase (implicit flow)
[[redirects]]
  from = "/?code=*"
  to = "/confirmed?code=:code"
  status = 302
  force = true

# Handle auth callback redirects (PKCE flow)
[[redirects]]
  from = "/?token_hash=*&type=*"
  to = "/confirmed?token_hash=:token_hash&type=:type"
  status = 302
  force = true

# Handle error redirects with OTP issues
[[redirects]]
  from = "/?error=*&error_code=*&error_description=*"
  to = "/confirmed?error=:error&error_code=:error_code&error_description=:error_description"
  status = 302
  force = true

# Handle QR code invitation redirects
[[redirects]]
  from = "/register?invitation=*&code=*"
  to = "/app/register?invitation=:invitation&code=:code"
  status = 302

# Handle QR scan redirects
[[redirects]]
  from = "/register?from=qr_scan&connect=*"
  to = "/app/register?from=qr_scan&connect=:connect"
  status = 302

# Handle QR scan with scan ID
[[redirects]]
  from = "/register?from=qr_scan&connect=*&scan_id=*"
  to = "/app/register?from=qr_scan&connect=:connect&scan_id=:scan_id"
  status = 302

# SPA routing - specific routes only (excludes assets)
[[redirects]]
  from = "/confirmed"
  to = "/index.html"
  status = 200

# Specific app routes instead of wildcard
[[redirects]]
  from = "/app/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/app/register"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/app/onboarding"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/app/home"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/app/profile"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/app/settings"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/app/reset-password"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/waitlist"
  to = "/index.html"
  status = 200

# QR Code public profile routes
[[redirects]]
  from = "/profile/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/connect/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/share/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/story"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/verify"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/confirm"
  to = "/index.html"
  status = 200

# Removed /share/* redirect to prevent asset interference

[[redirects]]
  from = "/demo"
  to = "/index.html"
  status = 200

# Explicit redirects for app routes (excluding assets)
# Removed /profile/* and /connect/* redirects to prevent asset interference

# Note: Removed catch-all redirect to prevent asset interference
# Assets should be served directly by Netlify without redirects

# Headers for better security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
           Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://bbonxxvifycwpoeaxsor.supabase.co https://*.supabase.co; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https: blob:; connect-src 'self' https://bbonxxvifycwpoeaxsor.supabase.co https://*.supabase.co wss://bbonxxvifycwpoeaxsor.supabase.co https://o4510074051756032.ingest.us.sentry.io https://*.ingest.us.sentry.io https://nominatim.openstreetmap.org https://fonts.googleapis.com; frame-src 'self' https://bbonxxvifycwpoeaxsor.supabase.co; worker-src 'self' blob:; object-src 'none'; base-uri 'self';"
    Permissions-Policy = "geolocation=*"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for JavaScript modules
[[headers]]
  for = "/assets/js/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for CSS files
[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[dev]
  command = "pnpm dev"
  port = 3001  # ✅ FIXED: Match vite config
  publish = "dist"
  autoLaunch = true

# Function settings removed - not using Netlify functions
